---
name: Continuous Integration (CI)

# Run CI jobs on all branches and pull requests
on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py collectstatic --no-input
          coverage run --source="." python manage.py test --testrunner "xmlrunner.extra.djangotestrunner.XMLTestRunner"
          coverage report --show-missing
          coverage xml
      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: ${{ always() }}
        with:
          check_name: Test Report
          include_passed: true
          report_paths: "TEST-*.xml"
      - name: Create code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          indicators: true
          output: both