---
name: Continuous Integration

on:
  # Run CI jobs on all branches and pull requests
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2